# Numpy
##### By-Dilpreet Kaur

NumPy (Numerical Python) is an open-source Python library used for fast numerical computations and multi-dimensional array operations. It provides a powerful ndarray object and many mathematical functions.

### Features of NumPy

1. Fast execution (implemented in optimized C under the hood)
2. Efficient memory usage
3. Supports 1D, 2D, 3D, and N-dimensional arrays
4. Vectorized operations (operate on entire arrays without explicit loops)
5. Broadcasting for operations on arrays of different shapes
6. Rich collection of mathematical, statistical, and linear algebra functions
7. Easy integration with other data science libraries

| Python List                           | NumPy Array                    |
| ------------------------------------- | ------------------------------ |
| Slower                                | Faster                         |
| Uses more memory                      | Uses less memory               |
| Stores different data types           | Usually stores one data type   |
| Mathematical operations require loops | Supports vectorized operations |
| Used for general programming          | Used for numerical computing   |


In [1]:
import numpy as np

# 1. Array creation

In [2]:
# list
a=[1,2,34,98]
print(a,type(a))
# 1D array-Notice there are no commas in the printed output. That's NumPy's display format.
b=np.array([1,2,34,98])
print(b,type(b))

print(np.version)


[1, 2, 34, 98] <class 'list'>
[ 1  2 34 98] <class 'numpy.ndarray'>
<module 'numpy.version' from 'C:\\Users\\dilpr\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\numpy\\version.py'>


In [3]:
#2D array-like a table-imagine u are assigning values to one row in []
c=np.array([[1,2],[3,9],[34,76]])
print(c,type(c))
#3D Array-like a matrix having multiple sheets of tables
d=np.array([[[1,2,6],[6,5,2]],[[87,32,678],[1,7,4]]])
print(d)

[[ 1  2]
 [ 3  9]
 [34 76]] <class 'numpy.ndarray'>
[[[  1   2   6]
  [  6   5   2]]

 [[ 87  32 678]
  [  1   7   4]]]


##### Array with values of different datatype
NumPy arrays are homogeneous, so all elements are converted to a common compatible data type. However, you can explicitly create a mixed-type array using dtype=object, though this sacrifices many of NumPy's performance benefits.

bool

   ↓

int

   ↓

float

   ↓

complex

   ↓

string (Unicode)

   ↓

object (only if explicitly specified or required)

The data type lower in the hierarchy "wins" because it can represent the types above it.
##### Whenever a string is mixed with numeric values, the result is a Unicode string dtype.
| Input Data Types               | Resulting dtype |
| ------------------------------ | --------------- |
| `bool + bool`                  | `bool`          |
| `bool + int`                   | `int64`         |
| `bool + float`                 | `float64`       |
| `bool + complex`               | `complex128`    |
| `int + int`                    | `int64`         |
| `int + float`                  | `float64`       |
| `int + complex`                | `complex128`    |
| `float + float`                | `float64`       |
| `float + complex`              | `complex128`    |
| `complex + complex`            | `complex128`    |
| `bool + int + float`           | `float64`       |
| `bool + int + complex`         | `complex128`    |
| `int + float + complex`        | `complex128`    |
| `bool + int + float + complex` | `complex128`    |


In [4]:
e=np.array([1,8.9,4+3j])
print(e,e.dtype)
print(np.array([9+6j,3,8,999.3,"Hi"]).dtype)

[1. +0.j 8.9+0.j 4. +3.j] complex128
<U64


# 2. Array Atrributes

| Attribute  | Description                                                 | Returns          | Example                   |
| ---------- | ----------------------------------------------------------- | ---------------- | ------------------------- |
| `ndim`     | Number of dimensions (axes)                                 | `int`            | `arr.ndim` → `2`          |
| `shape`    | Size of each dimension                                      | `tuple`          | `arr.shape` → `(3, 4)`    |
| `size`     | Total number of elements                                    | `int`            | `arr.size` → `12`         |
| `dtype`    | Data type of array elements                                 | `numpy.dtype`    | `arr.dtype` → `int64`     |
| `itemsize` | Memory occupied by one element (in bytes)                   | `int`            | `arr.itemsize` → `8`      |
| `nbytes`   | Total memory occupied by the array (in bytes)               | `int`            | `arr.nbytes` → `96`       |
| `T`        | Transpose of the array                                      | `ndarray`        | `arr.T`                   |
| `real`     | Real part of the array                                      | `ndarray`        | `arr.real`                |
| `imag`     | Imaginary part of the array                                 | `ndarray`        | `arr.imag`                |
| `flat`     | 1D iterator over all elements in one by one use it as u use iterator in python                              | `numpy.flatiter` | `arr.flat`                |
| `strides`  | Number of bytes to move to the next element along each axis | `tuple`          | `arr.strides` → `(32, 8)` |
| `flags`    | Memory layout information (C-contiguous, writable, etc.)    | `numpy.flagsobj` | `arr.flags`               |


##### nbytes = size × itemsize

In [5]:
d = np.array([
    [[1,2,6],[6,5,2]],
    [[87,32,678],[1,7,4]]
])

print(d)
print("dimensons : ", d.ndim)
print("shape : ",d.shape)
# 2 blocks (outermost dimension)
# Each block has 2 rows
# Each row has 3 columns
print("size : ",d.size)
print("datatype : ",d.dtype)
print("memory occupied by one element : ",d.itemsize)
print("total memory occupied by array : ",d.nbytes)
print("Transpose : ",d.T)
print("Shape of transpose of array : ",d.T.shape)
print("how array stored in memory : ",d.flags)
# print("real part",d.real)
print(d.strides)
# (48, 24, 8)...means from 1 to 87 it takes 48 bytes(6 element *8 bytes each) and from 1 to 6 it takes 24 bytes(3 elements * 8 bytes each ) and from 1 to 2 it takes only 8 bytes

[[[  1   2   6]
  [  6   5   2]]

 [[ 87  32 678]
  [  1   7   4]]]
dimensons :  3
shape :  (2, 2, 3)
size :  12
datatype :  int64
memory occupied by one element :  8
total memory occupied by array :  96
Transpose :  [[[  1  87]
  [  6   1]]

 [[  2  32]
  [  5   7]]

 [[  6 678]
  [  2   4]]]
Shape of transpose of array :  (3, 2, 2)
how array stored in memory :    C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

(48, 24, 8)


# 3. Array Generation Functions

| Function        | Purpose                                                                     | Syntax                                                                       | Important Arguments                                    | Default `dtype`            | Example              |
| --------------- | --------------------------------------------------------------------------- | ---------------------------------------------------------------------------- | ------------------------------------------------------ | -------------------------- | -------------------- |
| `np.array()`    | Create an array from a list, tuple, or other sequence                       | `np.array(object, dtype=None)`                                               | `object`, `dtype`, `copy`, `ndmin`                     | Inferred from data         | `np.array([1,2,3])`  |
| `np.zeros()`    | Create an array filled with zeros                                           | `np.zeros(shape, dtype=float)`                                               | `shape`, `dtype`                                       | `float64`                  | `np.zeros((2,3))`    |
| `np.ones()`     | Create an array filled with ones                                            | `np.ones(shape, dtype=float)`                                                | `shape`, `dtype`                                       | `float64`                  | `np.ones((2,3))`     |
| `np.empty()`    | Create an uninitialized array (contains arbitrary values already in memory) | `np.empty(shape, dtype=float)`                                               | `shape`, `dtype`                                       | `float64`                  | `np.empty((2,2))`    |
| `np.full()`     | Create an array filled with a specified value                               | `np.full(shape, fill_value, dtype=None)`                                     | `shape`, `fill_value`, `dtype`                         | Inferred from `fill_value` | `np.full((2,2), 5)`  |
| `np.arange()`   | Generate evenly spaced values within a range                                | `np.arange(start, stop, step, dtype=None)`                                   | `start`, `stop`, `step`, `dtype`                       | Inferred                   | `np.arange(1,10,2)`  |
| `np.linspace()` | Generate a specified number of evenly spaced values between two endpoints   | `np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)` | `start`, `stop`, `num`, `endpoint`, `retstep`, `dtype` | `float64`                  | `np.linspace(0,1,5)` |
| `np.logspace()` | Generate numbers evenly spaced on a logarithmic scale                       | `np.logspace(start, stop, num=50, base=10)`                                  | `start`, `stop`, `num`, `base`, `dtype`                | `float64`                  | `np.logspace(1,3,3)` |
| `np.eye()`      | Create an identity matrix                                                   | `np.eye(N, M=None, k=0, dtype=float)`                                        | `N`, `M`, `k`, `dtype`                                 | `float64`                  | `np.eye(3)`          |
| `np.identity()` | Create a square identity matrix                                             | `np.identity(n, dtype=float)`                                                | `n`, `dtype`                                           | `float64`                  | `np.identity(4)`     |
| `np.diag()`     | Create a diagonal matrix or extract a diagonal                              | `np.diag(v, k=0)`                                                            | `v`, `k`                                               | Depends on input           | `np.diag([1,2,3])`   |
| `np.tri()`      | Create a lower triangular matrix                                            | `np.tri(N, M=None, k=0, dtype=float)`                                        | `N`, `M`, `k`, `dtype`                                 | `float64`                  | `np.tri(3)`          |


In [6]:
np.zeros((2,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [7]:
np.ones((2,3,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [8]:
np.empty((2,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [9]:
np.full((2,3,4),5)

array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])

In [10]:
np.eye(5,2)
# it can create any order of identity matrix

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.arange(1,32,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31])

In [13]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [14]:
np.logspace(1,5,10)
# give output in the power of 10

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [15]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

#### np.diag(v,k)

v: 1D or 2D array :	Required

k:	Diagonal index	: 0
| K Value | Meaning                              |
| ----- | ------------------------------------ |
| `0`   | Main diagonal                        |
| `1`   | One diagonal above the main diagonal |
| `2`   | Two diagonals above                  |
| `-1`  | One diagonal below the main diagonal |
| `-2`  | Two diagonals below                  |


In [16]:
# It has two different uses, depending on what you pass to it.
# Create a diagonal matrix from a 1D array.
arr1=np.diag([1,2,3])
arr2=np.diag([1,2,3],k=1)
print(arr1)
print(arr2)
# Extract the diagonal from a 2D array.
arr3=np.diag(np.array([[1,7,4],[9,3,2]]))
print(arr3)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]
[1 3]


# 4. NumPy Random Module
The NumPy Random module is used to generate random numbers, random arrays, random samples, and random selections.

| Python `random`                            | NumPy `random`                              |
| ------------------------------------------ | ------------------------------------------- |
| Generates one random value at a time       | Can generate entire arrays of random values |
| Slower for large datasets                  | Much faster (vectorized)                    |
| Used in general Python programming         | Used in Data Science, ML, AI                |
| Works with Python lists                    | Works directly with NumPy arrays            |
| Good for games, passwords, simple programs | Good for simulations, datasets, ML          |


| Function        | Purpose                                   | Python Equivalent                            |
| --------------- | ----------------------------------------- | -------------------------------------------- |
| `rand()`        | Random floats between 0 and 1             | `random.random()`                            |
| `randn()`       | Random numbers from a normal distribution | No direct equivalent                         |
| `randint()`     | Random integers                           | `random.randint()`                           |
| `random()`      | Random floats                             | `random.random()`                            |
| `choice()`      | Random selection                          | `random.choice()`                            |
| `shuffle()`     | Shuffle the original array                | `random.shuffle()`                           |
| `permutation()` | Return a shuffled copy                    | `random.sample()` *(similar, not identical)* |
| `seed()`        | Make results reproducible                 | `random.seed()`                              |


#### np.random.rand(size)

In [17]:
np.random.rand( ) #generate float number between 0 and 1


0.23324002203353744

In [18]:
np.random.rand(5)  #generate 5 uniformaly distributed float number between 0 and 1

array([0.76855997, 0.24742101, 0.18674745, 0.30415042, 0.58230955])

In [19]:
np.random.rand(2,3) #generate uniformaly distributed float number between 0 and 1 in the form of 2x3 array

array([[0.7731908 , 0.26273235, 0.21822144],
       [0.52882462, 0.72444129, 0.78856686]])

In [20]:
# but ramnom module in python can generate only one random number at a time
import random
print(random.random())

0.9659780710891426


#### np.random.randn(size)

In [21]:
np.random.randn()

-1.2857079961936213

In [22]:
np.random.randn(5) #Not limited to 0–1 only

array([-0.07088908, -2.05618698, -0.68222765, -1.23727507,  0.83156848])

In [23]:
np.random.randn(5,4)

array([[ 0.09049014,  0.32765723, -0.64820254, -0.00599392],
       [-1.68329469, -1.76810919,  0.04329909,  0.83596008],
       [-0.36970978, -0.5844085 , -0.07899395,  1.06163006],
       [ 1.84627746,  0.82747638, -0.83063034, -0.40944015],
       [ 0.98271441, -1.55960003,  1.093413  ,  1.70898837]])

#### np.random.randint(low, high=None, size=None)
it generate random integer values

In [24]:
np.random.randint(1,7,(2,4))

array([[2, 2, 3, 2],
       [2, 1, 6, 4]], dtype=int32)

In [25]:
np.random.randint(1,7,4)

array([2, 4, 1, 3], dtype=int32)

#### np.random.choice(arr, no. of selection)
Randomly selects values from a sequence(1D).

In [26]:
np.random.choice([0.05654264, -0.269237  , -0.00776113,  0.0097719 ]       )

np.float64(0.05654264)

In [27]:
np.random.choice([0.05654264, -0.269237  , -0.00776113,  0.0097719 ],3)

array([0.0097719 , 0.0097719 , 0.05654264])

#### np.random.shuffle(arr)
Shuffles the original array.

In [28]:
arr3=np.array([1,7,34,21])
print("array before shuffling ",arr3)
np.random.shuffle(arr3)
print("array after shuffling",arr3)

array before shuffling  [ 1  7 34 21]
array after shuffling [ 7 21 34  1]


#### np.random.permutation()
Returns a shuffled copy.no effect on original array.


In [29]:
arr4=np.array([91,70,34,201])
result=np.random.permutation(arr4)
print(result)
print(arr4)

[201  34  91  70]
[ 91  70  34 201]


#### np.random.seed(value)
initializes NumPy's random number generator with a fixed starting point so that the same sequence of pseudo-random numbers is produced every time the program runs.

In [30]:
np.random.seed(10)
np.random.random((1,5))

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701]])

# 5. Array Methods

| Function (Syntax)                                  | Purpose                                   | Important Arguments           |
| -------------------------------------------------- | ----------------------------------------- | ----------------------------- |
| `arr.reshape(shape, order='C')`                    | Change array shape                        | `shape`, `order`              |
| `arr.resize(new_shape, refcheck=True)`             | Resize array                              | `new_shape`, `refcheck`       |
| `arr.flatten(order='C')`                           | Return a flattened **copy**               | `order`                       |
| `arr.ravel(order='C')`                             | Return a flattened **view** (if possible) | `order`                       |
| `arr.transpose(*axes)` or `arr.T`                  | Transpose array                           | `axes`                        |
| `arr.squeeze(axis=None)`                           | Remove dimensions of size 1               | `axis`                        |
| `np.expand_dims(arr, axis)`                        | Add a new axis                            | `axis`                        |
| `np.concatenate((a, b), axis=0)`                   | Join arrays                               | `arrays`, `axis`              |
| `np.stack((a, b), axis=0)`                         | Stack arrays along a new axis             | `arrays`, `axis`              |
| `np.hstack((a, b))`                                | Stack arrays horizontally                 | `arrays`                      |
| `np.vstack((a, b))`                                | Stack arrays vertically                   | `arrays`                      |
| `np.dstack((a, b))`                                | Stack arrays along the third axis         | `arrays`                      |
| `np.split(arr, indices_or_sections, axis=0)`       | Split array equally                       | `indices_or_sections`, `axis` |
| `np.array_split(arr, indices_or_sections, axis=0)` | Split array equally or unequally          | `indices_or_sections`, `axis` |
| `arr.copy()`                                       | Create a deep copy (independent array)    | —                             |
| `arr.view(dtype=None)`                             | Create a shallow copy (shares memory)     | `dtype`                       |
| `arr.astype(dtype, copy=True)`                     | Convert array to another data type        | `dtype`, `copy`               |
| `np.clip(arr, a_min, a_max)`                       | Limit values within a specified range     | `a_min`, `a_max`              |
| `np.repeat(arr, repeats, axis=None)`               | Repeat each element                       | `repeats`, `axis`             |
| `np.tile(arr, reps)`                               | Repeat the entire array                   | `reps`                        |
| `np.round(arr, decimals=0)`                        | Round values to the specified decimals    | `decimals`                    |


## 1. arr.reshape()
reshape() changes the shape (dimensions) of an array without changing its data.
* Rule: The total number of elements must remain the same.

it returns a view not a copy

Using -1.Instead of calculating one dimension yourself, let NumPy calculate it.

In [31]:
arr8 = np.array([1,2,3,4,5,6])
print(arr8.reshape((2,3)))
print(arr8.reshape((3,2)))
print(arr8.reshape((1,6)))
print(arr8.reshape((6,1)))
print(arr8)
print(arr8.reshape((2,-1)))


[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


## 2. resize()
resize() changes the shape and size of an array.It can increase or decrease the total number of elements.

| Type         | Syntax         | Original Array Modified? |
| ------------ | -------------- | ------------------------ |
| **Method**   | `arr.resize()` | ✅ Yes                    |
| **Function** | `np.resize()`  | ❌ No                     |


### (i) arr.resize(new_shape, refcheck=True)
            vs
### (ii) np.resize(arr,size)

In [32]:
arr9=np.array([1,72,3,4,5,67,8])
print("original array ",arr9)
arr9.resize((3,4))
# If the array grows:
# Zeros are added.
print("after using arr.resize..if array size inc zeros are added :", arr9)


print("output of np.resize..if array size inc elements gets repeated :",np.resize(arr9,(5,3)))
print("original array :",arr9)

original array  [ 1 72  3  4  5 67  8]
after using arr.resize..if array size inc zeros are added : [[ 1 72  3  4]
 [ 5 67  8  0]
 [ 0  0  0  0]]
output of np.resize..if array size inc elements gets repeated : [[ 1 72  3]
 [ 4  5 67]
 [ 8  0  0]
 [ 0  0  0]
 [ 1 72  3]]
original array : [[ 1 72  3  4]
 [ 5 67  8  0]
 [ 0  0  0  0]]


## 3. np.concatenate((arr1, arr2), axis=0)
Joins arrays along an existing axis.It does not create a new dimension.

Axis 0 → Rows (vertical direction ⬇️)(Number of columns must be the same.)

Axis 1 → Columns (horizontal direction ➡️)(Number of rows must be the same.)

This is the key to understanding joining functions.

In [33]:
arr10=np.array([[1,2,7],[9,3,6]])
arr11=np.array([[87,32,12],[7,23,67]])
print(arr10)
print(" ")
print(arr11)
print(' ')
print(np.concatenate((arr10,arr11),axis=0))
print("  ")
print(np.concatenate((arr10,arr11),axis=1))
print("  ")
print(np.concatenate((arr10,arr11)))
print("  ")
print(np.concatenate(([1,2,3],[9,8,7]),axis=0))
print("  ")
# print(np.concatenate(([1,2,3],[9,8,7]),axis=1))AxisError: axis 1 is out of bounds for array of dimension 1

[[1 2 7]
 [9 3 6]]
 
[[87 32 12]
 [ 7 23 67]]
 
[[ 1  2  7]
 [ 9  3  6]
 [87 32 12]
 [ 7 23 67]]
  
[[ 1  2  7 87 32 12]
 [ 9  3  6  7 23 67]]
  
[[ 1  2  7]
 [ 9  3  6]
 [87 32 12]
 [ 7 23 67]]
  
[1 2 3 9 8 7]
  


## 4. np.stack((arr1, arr2, ...), axis=0) 
stack() creates a brand-new axis.

stack() always increases the number of dimensions by 1.


In [34]:
a = np.array([1,2,3])# this is of order 3
b = np.array([4,5,6])# this is of order 3
print(np.stack((a,b)))#2D array of order 2x3
print(" ")
print(np.stack((a,b),axis=0))
print(" ")
print(np.stack((a,b),axis=1))#2D array of order 3x2

[[1 2 3]
 [4 5 6]]
 
[[1 2 3]
 [4 5 6]]
 
[[1 4]
 [2 5]
 [3 6]]


## 5. Vertical Stack (np.vstack(arr1,arr2))
Think of putting one array below another.

In [35]:
a = np.array([1,2,3])# this is of order 3
b = np.array([4,5,6])# this is of order 3
print(np.vstack((a,b)))#2D array of order 2x3

[[1 2 3]
 [4 5 6]]


## 6. Horizontal Stack (np.hstack(arr1,arr2))
Now imagine placing arrays side by side.

In [36]:
import numpy as np
a = np.array([1,2,3])# this is of order 3
b = np.array([4,5,6])# this is of order 3
print(np.hstack((a,b)))#1D array of order 6
print(" ")
c = np.array([[1],
              [2],
              [3]])

d = np.array([[4],
              [5],
              [6]])
print(np.hstack((c,d)))

[1 2 3 4 5 6]
 
[[1 4]
 [2 5]
 [3 6]]


## 7. Column Stack (np.column_stack())
This is commonly used in data analysis.



In [37]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

## 8. Row Stack (np.row_stack())



In [38]:
np.row_stack((a,b))

C:\Users\dilpr\AppData\Local\Temp\ipykernel_5308\1307586492.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[1, 2, 3],
       [4, 5, 6]])

| Function        | Works On   | Description              |
| --------------- | ---------- | ------------------------ |
| `split()`       | 1D, 2D, 3D | Equal split only         |
| `array_split()` | 1D, 2D, 3D | Unequal split allowed    |
| `vsplit()`      | 2D         | Split rows (`axis=0`)    |
| `hsplit()`      | 2D         | Split columns (`axis=1`) |


## 9. np.split(array, sections, axis=0)
Splits an array into equal parts.

#### The division must be exact.Otherwise
ValueError:
array split does not result in an equal division

In [39]:
import numpy as np
arr=np.array([10,20,40,60,20,0])
print(np.split(arr,3))

[array([10, 20]), array([40, 60]), array([20,  0])]


## 10. np.array_split()
This is much smarter.

#### It doesn't require equal division.

In [40]:
arr=np.arange(10);
print(np.array_split(arr,3))

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


## 11. np.hsplit(arr,size)
Shortcut for splitting columns.

In [41]:
arr=np.arange(16).reshape(2,8)
print(arr)
print(" ")
print(np.hsplit(arr,2))

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
 
[array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]]), array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])]


## 12. np.vsplit(arr,size)
Shortcut for splitting rows.

In [42]:
arr=np.arange(16).reshape(2,8)
print(arr)
print(" ")
print(np.vsplit(arr,2))

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
 
[array([[0, 1, 2, 3, 4, 5, 6, 7]]), array([[ 8,  9, 10, 11, 12, 13, 14, 15]])]


## 13. arr.flatten()

flatten() converts a multi-dimensional array into a 1D array.

* Most important point : It creates a copy of the original array.

In [43]:
arr=np.array([[1,2,3],[7,3,8]]);
flat=arr.flatten()
print(flat)
print(arr.shape)
print(flat.shape)

flat[0] = 100
print(" ")
print(flat)
print(arr) #The original array did not change.

[1 2 3 7 3 8]
(2, 3)
(6,)
 
[100   2   3   7   3   8]
[[1 2 3]
 [7 3 8]]


## 14. arr.ravel()
ravel() also converts an array into 1D, but it tries to return a view instead of a copy.

ravel() returns a view whenever possible; if a view isn't possible (for example, with some non-contiguous arrays), it returns a copy.

In [44]:
arr = np.array([[1,2,3],
                [4,5,6]])

rav = arr.ravel()

print(rav)

rav[0] = 100

print(rav)
print(arr) #The original array changed too!

[1 2 3 4 5 6]
[100   2   3   4   5   6]
[[100   2   3]
 [  4   5   6]]


| flatten()               | ravel()                  |
| ----------------------- | ------------------------ |
| Copy                    | View (whenever possible) |
| More memory             | Less memory              |
| Original doesn't change | Original may change      |
| Slower                  | Faster                   |



# SHALLOW COPY VS DEEP COPY


| Operation                   | Python Object    | Underlying Data      | Changes Affect Original?     |
| --------------------------- | ---------------- | -------------------- | ---------------------------- |
| `b = a`                     | Same object      | Same                 | ✅ Yes                        |
| `copy.copy()` (Python list) | New outer object | Inner objects shared | ✅ Sometimes (nested objects) |
| `copy.deepcopy()`(Python list)           | New object       | New data             | ❌ No                         |
| `a.view()` (NumPy)          | New array object | Shared data          | ✅ Yes                        |
| `a.copy()` (NumPy)          | New array object | New data             | ❌ No                         |
| `a[2:6]` (NumPy slice)      | New array object | Shared data (view)   | ✅ Yes                        |


* Shallow copy: Copies only the outer container. Nested mutable objects are shared.
    
* Deep copy: Recursively copies all nested objects, creating a completely independent structure.

In [45]:
#Assignment- a and b point to the same object.
a=[45]
b=a
print(a,"",b)
b[0]=67
print(a,"",b)
print(id(a))
print(id(b))

[45]  [45]
[67]  [67]
1187066876672
1187066876672


## Copying in Python

### 1. SHALLOW COPY

In [46]:
import numpy as np
# SHALLOW COPY
import copy
a=[[1,3,45],[9,3,7]]
b=copy.copy(a)
print(a,"    ",b)
print(" ")


b[0][0]=67
# Both changed.
print(a,"    ",b)
print(" ")

# Now only b changes.
# Because the outer list itself was copied.
b[0] = [9, 9]
print(" ")
print(a)
print(" ")
print(b)

[[1, 3, 45], [9, 3, 7]]      [[1, 3, 45], [9, 3, 7]]
 
[[67, 3, 45], [9, 3, 7]]      [[67, 3, 45], [9, 3, 7]]
 
 
[[67, 3, 45], [9, 3, 7]]
 
[[9, 9], [9, 3, 7]]


### 2. DEEP COPY

In [47]:
import copy

a = [[1,2],[3,4]]

b = copy.deepcopy(a)
b[0][0] = 100
# only b change
print(a)
print(b)

[[1, 2], [3, 4]]
[[100, 2], [3, 4]]


## Copying in Numpy

## 1. View

In [48]:
arr=np.array([[1,8,4],[9,3,6]])
brr=arr.view()
print(arr)
print(" ")
print(brr)
print(" ")


brr[0][0]=67
print(arr)
print(" ")
print(brr)
print(" ")
print(" ")


crr=arr[:]
crr[0][0]=34098
print(arr)
print(" ")
print(brr)
print(" ")
print(crr)
print(" ")
print(" ")

crr=arr[:]
crr[0]=[34098,7899,4567]
# means

# "I replaced the row, so only crr should change."

# That's true for Python lists in some shallow-copy situations, but not for NumPy views.
print(arr)
print(" ")
print(brr)
print(" ")
print(crr)
print(" ")
print(" ")

[[1 8 4]
 [9 3 6]]
 
[[1 8 4]
 [9 3 6]]
 
[[67  8  4]
 [ 9  3  6]]
 
[[67  8  4]
 [ 9  3  6]]
 
 
[[34098     8     4]
 [    9     3     6]]
 
[[34098     8     4]
 [    9     3     6]]
 
[[34098     8     4]
 [    9     3     6]]
 
 
[[34098  7899  4567]
 [    9     3     6]]
 
[[34098  7899  4567]
 [    9     3     6]]
 
[[34098  7899  4567]
 [    9     3     6]]
 
 


In [49]:
arr=np.array([[1,8,4],[9,3,6]])
brr=arr.copy()
print(arr)
print(" ")
print(brr)
print(" ")


brr[0][0]=67
print(arr)
print(" ")
print(brr)
print(" ")
print(" ")


crr=arr.copy()
crr[0][0]=34098
print(arr)
print(" ")
print(brr)
print(" ")
print(crr)
print(" ")
print(" ")

crr=arr.copy()
crr[0]=[34098,7899,4567]
print(arr)
print(" ")
print(brr)
print(" ")
print(crr)
print(" ")
print(" ")

[[1 8 4]
 [9 3 6]]
 
[[1 8 4]
 [9 3 6]]
 
[[1 8 4]
 [9 3 6]]
 
[[67  8  4]
 [ 9  3  6]]
 
 
[[1 8 4]
 [9 3 6]]
 
[[67  8  4]
 [ 9  3  6]]
 
[[34098     8     4]
 [    9     3     6]]
 
 
[[1 8 4]
 [9 3 6]]
 
[[67  8  4]
 [ 9  3  6]]
 
[[34098  7899  4567]
 [    9     3     6]]
 
 


# 6. NumPy Arithmetic Functions

| Function                  | Purpose                    |
| ------------------------- | -------------------------- |
| `+`, `np.add()`           | Addition                   |
| `-`, `np.subtract()`      | Subtraction                |
| `*`, `np.multiply()`      | Multiplication             |
| `/`, `np.divide()`        | Division                   |
| `//`, `np.floor_divide()` | Floor division             |
| `%`, `np.mod()`           | Modulus                    |
| `**`, `np.power()`        | Power                      |
| `np.abs()`                | Absolute value             |
| `np.square()`             | Square                     |
| `np.sqrt()`               | Square root                |
| `np.cbrt()`               | Cube root                  |
| `np.exp()`                | Exponential (eˣ)           |
| `np.log()`                | Natural logarithm          |
| `np.log10()`              | Base-10 logarithm          |
| `np.log2()`               | Base-2 logarithm           |
| `np.reciprocal()`         | Reciprocal (1/x)           |
| `np.sign()`               | Sign of elements           |
| `np.clip()`               | Restrict values to a range |
| `np.maximum()`            | Element-wise maximum       |
| `np.minimum()`            | Element-wise minimum       |
| `np.round()`              | Round values               |
| `np.floor()`              | Round down                 |
| `np.ceil()`               | Round up                   |
| `np.trunc()`              | Remove fractional part     |
| `np.isnan()`              | Check for NaN              |
| `np.isinf()`              | Check for infinity         |
| `np.isfinite()`           | Check for finite values    |


## 1. Basic Arithmetic Operators

In [50]:
import numpy as np

a = np.array([10,20,30])
b = np.array([1,2,3])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(a**b)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]
[10 10 10]
[0 0 0]
[   10   400 27000]


## 2. Arithmetic Functions

In [51]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.floor_divide(a,b))
print(np.mod(a,b))
print(np.power(a,b))

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]
[10 10 10]
[0 0 0]
[   10   400 27000]


## 3. Absolute Value

In [52]:

arr=np.array([-5,-10,8,-3])

print(np.abs(arr))

[ 5 10  8  3]


## 4. Square


In [53]:
arr=np.array([2,3,4])

print(np.square(arr))

[ 4  9 16]


## 5. Square Root 

In [54]:

arr=np.array([1,4,9,16])

print(np.sqrt(arr))

[1. 2. 3. 4.]


## 6. Cube Root (Indirect) 

In [55]:
arr=np.array([1,8,27,64])
print(np.cbrt(arr))
print(arr**(1/3))

[1. 2. 3. 4.]
[1. 2. 3. 4.]


## 7. Exponential 
Calculates eˣ


In [56]:

arr=np.array([1,2,3])

print(np.exp(arr))

[ 2.71828183  7.3890561  20.08553692]


## 8. Maximum & Minimum 

In [57]:

a=np.array([3,8,5])

b=np.array([5,4,7])

print(np.maximum(a,b))
print(np.minimum(a,b))

[5 8 7]
[3 4 5]


## 9.  Logarithms

In [58]:
arr=np.array([1,10,100])

print(np.log10(arr))
print(np.log2(arr))
print(np.log(arr))

[0. 1. 2.]
[0.         3.32192809 6.64385619]
[0.         2.30258509 4.60517019]


## 10. Rounding Functions

In [59]:
arr=np.array([2.345,6.789])
print(np.round(arr,2))

#Floor-round down
print(np.floor(arr))

#Ceil-round up
print(np.ceil(arr))

#Trunc-remove decimal part
arr=np.array([-3.9,2.8])
print(np.trunc(arr))

[2.35 6.79]
[2. 6.]
[3. 7.]
[-3.  2.]


# 7.NumPy Aggregation (Reduction) Functions
Aggregation means taking many values and reducing them to one value.

| Function (Syntax)                                  | Purpose                                                                   |
| -------------------------------------------------- | ------------------------------------------------------------------------- |
| `arr.sum(axis=None)`                               | Sum of all elements. Use `axis=0` for column-wise, `axis=1` for row-wise. |
| `arr.min(axis=None)`                               | Smallest value.                                                           |
| `arr.max(axis=None)`                               | Largest value.                                                            |
| `arr.mean(axis=None)`                              | Arithmetic mean (average).                                                |
| `np.median(arr, axis=None)`                        | Median (middle value after sorting).                                      |
| `np.std(arr, axis=None)`                           | Standard deviation (spread of data).                                      |
| `np.var(arr, axis=None)`                           | Variance.                                                                 |
| `arr.prod(axis=None)` or `np.prod(arr, axis=None)` | Product of all elements.                                                  |
| `arr.argmax(axis=None)`                            | Index of the maximum value.                                               |
| `arr.argmin(axis=None)`                            | Index of the minimum value.                                               |
| `arr.cumsum(axis=None)`                            | Cumulative sum.                                                           |
| `arr.cumprod(axis=None)`                           | Cumulative product.                                                       |
| `np.percentile(arr, q, axis=None)`                 | q-th percentile (e.g., `q=25`, `50`, `75`).                               |
| `np.quantile(arr, q, axis=None)`                   | Quantile (`q` between `0` and `1`).                                       |
| `np.any(arr, axis=None)`                           | Returns `True` if **at least one** element is `True`.                     |
| `np.all(arr, axis=None)`                           | Returns `True` if **all** elements are `True`.                            |


## 1. arr.sum(axis=None)

In [61]:
arr=np.array([[1,2],
              [3,4]])
print(arr.sum())
print(arr.sum(axis=0))
print(arr.sum(axis=1))

10
[4 6]
[3 7]


## 2. arr.min(axis=None)

In [65]:
print(arr.min())
print(arr.min(axis=0))
print(arr.min(axis=1))

1
[1 2]
[1 3]


## 3. arr.max(axis=None)

In [64]:
print(arr.max())
print(arr.max(axis=0))
print(arr.max(axis=1))

4
[3 4]
[2 4]


## 4. arr.mean(axis=None)
Returns the arithmetic average.

In [66]:
arr.mean()

np.float64(2.5)

## 5. np.median(arr, axis=None)
returns the middle value after sorting.

In [68]:
np.median(arr)

np.float64(2.5)

## 6. np.std(arr, axis=None, ddof=0, keepdims=False)
Returns the standard deviation.
Measures how spread out data is from the mean.

In [69]:
np.std([2,4,6,8])

np.float64(2.23606797749979)

## 7. np.var(arr, axis=None)

Returns the variance.

#### Formula

#### Variance = (Standard Deviation)²

In [70]:
np.var([2,4,6,8])

np.float64(5.0)

## 8. arr.prod(axis=None)
Returns the product of all elements.

In [71]:
arr=np.array([2,3,4])

arr.prod()

np.int64(24)

## 9. arr.argmax(axis=None)
Returns the index of the maximum value.

In [72]:
a=np.array([12,56,245,78])
a.argmax()

np.int64(2)

## 10. arr.argmix(axis=None)
Returns the index of the minimum value.

In [73]:
a=np.array([12,56,245,78])
a.argmin()

np.int64(0)

## 11. arr.cumsum(axis=None)
Returns cumulative sum.

In [75]:
arr=np.array([2,4,6])

arr.cumsum()

array([ 2,  6, 12])

## 12. np.percentile(arr, q, axis=None)

Returns the q-th percentile.

Important Argument:q=0–100

In [76]:
arr=np.array([10,20,30,40,50])

np.percentile(arr,50)

np.float64(30.0)

## 13. np.quantile(arr, q, axis=None)
Returns the quantile.

In [77]:
np.quantile(arr,0.5)

np.float64(30.0)

Percentage → "How much of the whole?" (e.g., 90% marks)

Percentile → "Where do I stand among others?" (e.g., 90th percentile-Higher than 90% of people)

Quantile → "What fraction of the data am I looking at?...Quantile is simply the fractional version of percentile." (0 to 1 scale)

Quartile → "Split the data into 4 equal groups" (Q1, Q2, Q3)

# 8. Sorting

Sorting means arranging elements in an order.

Note: NumPy does not have a direct descending sort function. We usually sort in ascending order and then reverse the result.

## 1. np.sort(arr, axis=-1, kind='quicksort')
Returns a new sorted array without changing the original array.
| Argument | Meaning                                                            |
| -------- | ------------------------------------------------------------------ |
| `arr`    | Input array                                                        |
| `axis`   | Axis to sort (`-1` by default)                                     |
| `kind`   | Sorting algorithm (`quicksort`, `mergesort`, `heapsort`, `stable`) |


In [1]:
import numpy as np

arr = np.array([8,3,9,1,5])

result = np.sort(arr)

print("Original :", arr)
print("Sorted   :", result)

Original : [8 3 9 1 5]
Sorted   : [1 3 5 8 9]


## 2. arr.sort() 
Sorts the array in-place.

In [2]:
arr = np.array([8,3,9,1,5])

arr.sort()

print(arr)

[1 3 5 8 9]


### 3. Sorting 2D Arrays

In [6]:
arr = np.array([[9,2,6],
                [4,8,1]])
print(arr)

# Default (axis=-1)
print(np.sort(arr))
print(np.sort(arr, axis=1))
# Each row is sorted independently.

#it sort each column independently
print(np.sort(arr, axis=0))

[[9 2 6]
 [4 8 1]]
[[2 6 9]
 [1 4 8]]
[[2 6 9]
 [1 4 8]]
[[4 2 1]
 [9 8 6]]


In [5]:
#To get descending order:

arr = np.array([8,3,9,1,5])

result = np.sort(arr)[::-1]

print(result)

[9 8 5 3 1]


### 4. np.argsort() 

This is one of the most asked interview questions.

It does NOT return sorted values.

It returns the indices that would sort the array.

In [7]:
arr = np.array([50,10,80,20])

print(np.argsort(arr))

[1 3 0 2]


# 9. Searching in NumPy 
Searching means finding:
* A value
* The index of a value
* Elements satisfying a condition
* Where a value should be inserted

| Function            | Purpose                                             |
| ------------------- | --------------------------------------------------- |
| `np.where()`        | Find indices or replace values based on a condition       |
| `np.nonzero()`      | Find indices of non-zero elements                         |
| `np.argwhere()`     | Return coordinates of matching elements                    |
| `np.searchsorted()` | Find insertion position in a sorted array                  |
| `np.extract()`      | Extract elements satisfying a condition                     |


## 1. np.where() 
This is the most important searching function in NumPy.
It has two different uses.

### Use 1: Find Indices-> np.where(condition)

In [9]:
import numpy as np

arr = np.array([10,20,30,20,50])

print(np.where(arr == 20))

(array([1, 3]),)


In [10]:
arr = np.array([[10,20],
                [30,40]])

print(np.where(arr > 20))

(array([1, 1]), array([0, 1]))


### Use 2: Conditional Replacement->np.where(condition, x, y)

In [11]:
arr = np.array([10,20,30,40])

result = np.where(arr > 25,100,0)

print(result)

[  0   0 100 100]


## 2. np.nonzero() 
Returns indices of non-zero elements.

In [12]:
arr=np.array([0,5,0,8,2])

print(np.nonzero(arr))

(array([1, 3, 4]),)


## 3. np.argwhere() 

Very similar to where().

Difference:

Instead of separate row/column arrays,

it returns coordinates.

In [13]:
arr=np.array([[10,20],
              [30,40]])

print(np.argwhere(arr>20))

[[1 0]
 [1 1]]


# 10. Boolean Indexing

Boolean indexing means selecting elements using True and False values.

Instead of giving NumPy indices, we give it a condition.

| Syntax                    | Purpose                             | Important Notes             |
| ------------------------- | ----------------------------------- | --------------------------- |
| `arr[arr > value]`        | Filter values greater than a number | Returns matching elements   |
| `arr[arr < value]`        | Filter values less than a number    | Returns matching elements   |
| `arr[arr == value]`       | Select equal values                 | Use `==`, not `=`           |
| `arr[arr != value]`       | Select values not equal             | Useful for excluding values |
| `arr[(cond1) & (cond2)]`  | AND condition                       | Use `&` and parentheses     |
| `arr[(cond1) \| (cond2)]` | OR condition                        | Use `\|` and parentheses    |
| `arr[~condition]`         | NOT condition                       | Inverts `True`/`False`      |
| `mask = arr > value`      | Create a Boolean mask               | Reusable for filtering      |
| `arr[condition] = value`  | Modify selected elements            | Changes the original array  |


In [14]:
arr = np.array([5, 10, 15, 20, 25])

arr[arr > 15]

array([20, 25])

In [15]:
arr = np.array([10, 20, 30, 40, 50])

arr > 25

array([False, False,  True,  True,  True])

In [16]:
arr = np.array([5, 10, 15, 20, 25, 30, 35])

arr[(arr > 10) & (arr < 30)]

array([15, 20, 25])

## Boolean Mask

Instead of writing the condition repeatedly, store it in a variable.

In [19]:
mask = arr > 20

print(mask)
print(arr[mask])

[False False False False  True  True  True]
[25 30 35]


## 1D Normal Indexing

In [21]:

import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[2])      # 30
print(arr[-1])     # 50

30
50


## 2D Normal Indexing

In [22]:
arr = np.array([[10, 20, 30],
                [40, 50, 60]])

print(arr[1])      # [40 50 60]  (2nd row)
print(arr[1][2])   # 60
# or
print(arr[1, 2])   # 60

[40 50 60]
60
60


## 3D Normal Indexing

In [23]:

arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(arr[0])          # First 2D array
print(arr[0, 1])       # [3 4]
print(arr[0, 1, 0])    # 3

[[1 2]
 [3 4]]
[3 4]
3
